sudo: required
language: python
python:
- '3.4'
- '3.5'
- '3.6'
addons:
  apt:
    packages:
    - libzmq-dev
install:
- python setup.py develop
- pip install -e .[dev]
script: pytest
notifications:
  slack:
    rooms:
      secure: sfs5sfKyLtWG0J601OYUXlNJDwFTdj67hSQqs56w8ejREpc27FFTcn1cLJc0O3WzP7XMEvxWy+U1aa0aK5Z6SNNzf7cWb4SV/6hcljIaYN84MTguZDP6HistWj2Os1CqDxM5Bimp56z0k1Z8GrzuHuEeJ6q/hU3iIYyAGaxbMQhicXR2oUp6UuNbiuIJKFHWlUEZc9/71Z7SIMYYr2TUMsABbvDfTWY9ilXvDEZmNI9qUY9VWaUWhV2xjj39HTew/f4+cUFmM9/KPH24y//2w8yoJssSykLmIuGFdkPBJd+5tcL4dD0wwBFQjsr9XONt0T0msEu2x6/RIVSCtz4x96Q9mEVFaTLTBHiBOKJwRnBzDP600mATcaQygCtEUTEf5wNO2HqYAf9mBzl5uPDXbsnr1KRB84LwQtskEhqQJPPF7B0hDv88SW2SLcakuLla6gsbt+su7V430OT2hU1gzUflSBXeqpHHKS9/J29+sYp+z0nn7LEMdN8QVl9Exele5dV1ZBaKcom2XJYXUBLcgkYTIMZeHS3iCTwy4W/AKVvvFtbajEPmiaSDD1CklTuiKdNZwFhNBaQ/oabkk4DTQaO0au+vD12aukbQVnKen1X1IkhbTEfb73z8ZWYZQ726ZFkjJdJWQo9tBT2Puezetf273LVsSqA+EvxgF17x/A4=
